<?php
	$this->grammar_tree = array(
		//	If Statement
		'/^(T_IF_START ((( T_AND | T_OR )?((T_VAR|T_STR|T_NUM) (T_IDENT|T_COMP) (T_VAR|T_STR|T_NUM))){1,}) T_OPEN_BLOCK)$/',
		// 	Else statement
		'/^(T_ELSE_START)$/',
		// 	Elseif statement
		'/^(T_ELIF_START ((( T_AND | T_OR )?((T_VAR|T_STR|T_NUM) (T_IDENT|T_COMP) (T_VAR|T_STR|T_NUM))){1,}) T_OPEN_BLOCK)$/',
		//	Assigning Variables
		'/^(T_VAR (T_EQUALS|T_MULTI_EQUAL|T_DIV_EQUAL|T_ADD_EQUAL|T_SUB_EQUAL|T_MOD_EQUAL|T_CONCAT_EQUAL) (T_NUM|T_STR|T_VAR|T_TRUE|T_FALSE))$/',
		//	Outputting Data to Screen
		'/^(T_PRINT (T_STR|T_NUM|T_VAR)( (T_CONCAT|T_ADD|T_MULTI|T_SUB|T_DIV|T_MOD) (T_STR|T_NUM|T_VAR)){0,})$/',
		// 	Closing all 
		'/^(T_CLOSE_BLOCK)$/',
		//	For Iterant
		'/^(T_FOR_START T_VAR T_EQUALS (T_VAR|T_NUM) T_SEPERATOR T_VAR (T_LESS_THAN_EQUAL|T_LESS_THAN|T_GRT_THAN_EQUAL|T_GRT_THAN|T_NOT_EQUAL) (T_NUM|T_VAR) T_SEPERATOR T_VAR (T_INCR|T_DECR|(T_ADD_EQUALS|T_SUB_EQUALS|T_MULTI_EQUALS|T_DIV_EQUALS|(T_EQUALS (T_SUB|T_ADD|T_DIV|T_MOD|T_MULTI) (T_VAR|T_NUM)))) T_OPEN_BLOCK)$/',
		//	While Iterant
		'/^(T_WHILE_START (T_VAR|T_STR|T_TRUE|T_FALSE|T_NUM) (T_LESS_THAN_EQUAL|T_LESS_THAN|T_GRT_THAN|T_GRT_THAN_EQUAL|T_NOT_EQUAL|T_NOT_IDENT|T_IDENT|T_COMP) (T_VAR|T_STR|T_TRUE|T_FALSE|T_NUM) T_OPEN_BLOCK)$/',
		// 	New Lines
		'/^(T_NEW_LINE)$/'
	);
?>